import enum


class RoleName(str, enum.Enum):
    CITIZEN = "CITIZEN"
    VOLUNTEER = "VOLUNTEER"
    AUTHORITY = "AUTHORITY"
    ADMIN = "ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"
    MODULE_DEVELOPER = "MODULE_DEVELOPER"


class BoundaryLevel(str, enum.Enum):
    VILLAGE = "VILLAGE"
    TOWN = "TOWN"
    URBAN_AREA = "URBAN_AREA"
    WARD = "WARD"
    BLOCK = "BLOCK"
    DISTRICT = "DISTRICT"


class AuthorityLevel(str, enum.Enum):
    LOCAL_BODY = "LOCAL_BODY"
    BLOCK_LEVEL = "BLOCK_LEVEL"
    DISTRICT_LEVEL = "DISTRICT_LEVEL"
    DEPARTMENT = "DEPARTMENT"


class Severity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ComplaintStatus(str, enum.Enum):
    REPORTED = "REPORTED"
    AI_ANALYZED = "AI_ANALYZED"
    ASSIGNED = "ASSIGNED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    VERIFICATION = "VERIFICATION"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"
    REOPENED = "REOPENED"


class NotificationType(str, enum.Enum):
    COMPLAINT_ASSIGNED = "COMPLAINT_ASSIGNED"
    DEADLINE_APPROACHING = "DEADLINE_APPROACHING"
    COMPLAINT_ESCALATED = "COMPLAINT_ESCALATED"
    COMPLAINT_RESOLVED = "COMPLAINT_RESOLVED"
    COMPLAINT_REJECTED = "COMPLAINT_REJECTED"
    COMPLAINT_REOPENED = "COMPLAINT_REOPENED"
    NEW_VOLUNTEER_EVENT = "NEW_VOLUNTEER_EVENT"
    GENERAL = "GENERAL"
